Info:
    dataset_name: truncmnist
Reader:
    name: CsvReader
    fn: input/smth_input.csv
    fn_labels: input/smth_target.csv
    has_header: False # provide True if it has headers
    sep: , # separator in csv file
    label_pos:
Preprocessor:
    name: BasicPreprocessor
Classifier:
    name: MLP
    splits:
    arch:
        h1: 30
        output: 10
    learning_rate:
    regularization:
